{{- if .Values.global.orbit.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "backbeat.fullname" . }}-gc-consumer
  labels:
    app: {{ template "backbeat.name" . }}-gc
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.garbageCollector.consumer.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "backbeat.name" . }}-gc
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.monitoring.annotations | indent 8 }}
    spec:
      containers:
        - name: gc-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          command: ["/usr/src/app/docker-entrypoint.sh"]
          args: ["npm", "run", "garbage_collector"]
          env:
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "{{- if .Values.global.orbit.enabled }}0{{- else }}1{{- end }}"
            - name: KAFKA_HOSTS
              value: "{{- printf "%s-zenko-queue:9092" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: EXTENSIONS_GC_AUTH_TYPE
              value: service
            - name: EXTENSIONS_GC_AUTH_ACCOUNT
              value: service-gc
            - name: CLOUDSERVER_HOST
              value: "{{- printf "%s-cloudserver" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: CLOUDSERVER_PORT
              value: "80"
            - name: MONGODB_HOSTS
              value: "{{ template "backbeat.mongodb-hosts" . }}"
            - name: COLLECT_DEFAULT_METRICS_INTERVAL_MS
              value: {{ quote .Values.monitoring.collectDefaultMetricsIntervalMs }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path.liveness}}
              port: {{ .Values.health.port }}
          resources:
{{ toYaml .Values.garbageCollector.consumer.resources | indent 12 }}
    {{- with .Values.garbageCollector.consumer.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.garbageCollector.consumer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.garbageCollector.consumer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
