apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "backbeat.fullname" . }}-replication-status-processor
  labels:
    app: {{ template "backbeat.name" . }}-replication
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replication.statusProcessor.replicaCount }}
  template:
    metadata:
      {{- if not .Values.global.orbit.enabled }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app: {{ template "backbeat.name" . }}-replication
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: replication-status-processor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/src/app/docker-entrypoint.sh"]
          args: ["npm", "run", "replication_status_processor"]
          env:
            - name: ZOOKEEPER_AUTO_CREATE_NAMESPACE
              value: "1"
            - name: ZOOKEEPER_CONNECTION_STRING
              value: "{{- printf "%s-zenko-quorum:2181" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: KAFKA_HOSTS
              value: "{{- printf "%s-zenko-queue:9092" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: MONGODB_HOSTS
              value: "{{ template "backbeat.mongodb-hosts" . }}"
            - name: EXTENSIONS_REPLICATION_SOURCE_S3_HOST
              value: "{{- printf "%s-cloudserver" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: EXTENSIONS_REPLICATION_SOURCE_S3_PORT
              value: "80"
            {{- if .Values.global.orbit.enabled }}
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "0"
            - name: EXTENSIONS_REPLICATION_SOURCE_AUTH_TYPE
              value: service
            - name: EXTENSIONS_REPLICATION_SOURCE_AUTH_ACCOUNT
              value: service-replication
            {{ else }}
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "1"
            - name: EXTENSIONS_REPLICATION_SOURCE_AUTH_TYPE
              value: account
            - name: EXTENSIONS_REPLICATION_SOURCE_AUTH_ACCOUNT
              value: Replication
            {{- end }}
            - name: REDIS_HOST
              value: "{{- printf "%s-%s" .Release.Name "redis-ha-master-svc" | trunc 63 | trimSuffix "-" -}}"
            - name: REDIS_PORT
              value: "6379"
            - name: LOG_LEVEL
              value: {{ .Values.logging.level }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path.liveness}}
              port: {{ .Values.health.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path.readiness }}
              port: {{ .Values.health.port }}
          resources:
{{ toYaml .Values.replication.statusProcessor.resources | indent 12 }}
    {{- with .Values.replication.statusProcessor.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.replication.statusProcessor.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.replication.statusProcessor.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
