apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "backbeat.fullname" . }}-api
  labels:
    app: {{ template "backbeat.name" . }}-api
    chart: {{ template "backbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "backbeat.name" . }}-api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "backbeat.fullname" . }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          args: ["npm", "start"]
          ports:
            - name: api
              containerPort: 8900
          env:
            - name: REMOTE_MANAGEMENT_DISABLE
              value: "{{- if .Values.global.orbit.enabled }}0{{- else }}1{{- end }}"
            - name: ZOOKEEPER_AUTO_CREATE_NAMESPACE
              value: "1"
            - name: ZOOKEEPER_CONNECTION_STRING
              value: "{{- printf "%s-zenko-quorum:2181" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: KAFKA_HOSTS
              value: "{{- printf "%s-zenko-queue:9092" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: EXTENSIONS_REPLICATION_SOURCE_S3_HOST
              value: "{{- printf "%s-cloudserver" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: EXTENSIONS_REPLICATION_SOURCE_S3_PORT
              value: "80"
            - name: REDIS_SENTINELS
              value: "{{ template "backbeat.redis-hosts" . }}"
            - name: REDIS_HA_NAME
              value: "{{ .Values.redis.sentinel.name }}"
            - name: HEALTHCHECKS_ALLOWFROM
              value: '0.0.0.0/0'
            - name: EXTENSIONS_REPLICATION_SOURCE_AUTH_ACCOUNT
              value: service-replication
            - name: EXTENSIONS_REPLICATION_DEST_BOOTSTRAPLIST
              value: "{{- printf "%s-cloudserver:80" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: MONGODB_HOSTS
              value: "{{ template "backbeat.mongodb-hosts" . }}"
            - name: PROMETHEUS_ENDPOINT
              value: "{{- printf "%s-prometheus-server:80" .Release.Name | trunc 63 | trimSuffix "-" -}}"
            - name: COLLECT_DEFAULT_METRICS_INTERVAL_MS
              value: {{ quote .Values.monitoring.collectDefaultMetricsIntervalMs }}
          livenessProbe:
            httpGet:
              path: /_/healthcheck
              port: api
          # TODO readinessProbe:
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
    {{- with .Values.api.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
