apiVersion: v1
kind: Service
metadata:
  {{- if .Values.blobserver.service.annotations }}
  annotations:
{{ toYaml .Values.blobserver.service.annotations | indent 4 }}
  {{- end }}
  name: {{ template "blobserver.fullname" . }}
  labels:
    app: {{ template "blobserver.name" . }}
    chart: {{ template "opal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.blobserver.service.type }}
  ports:
    - port: {{ .Values.blobserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "blobserver.name" . }}
    release: {{ .Release.Name }}
