# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: zookeeper
  tag: 3.4.11
  pullPolicy: IfNotPresent
service:
  name: zookeeper
persistentVolume:
  data:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    # TODO existingClaim: ""
    size: 1Gi
    # storageClass: "-"
  datalog:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    # TODO existingClaim: ""
    size: 10Gi
    # storageClass: "-"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
