{{- if .Values.maintenance.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "zenko.retry" . }}-failed
  labels:
{{ include "zenko.labels.standard" . | indent 4 }}
spec:
  schedule: "{{ .Values.maintenance.retryFailed.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.maintenance.successfulJobsHistory }}
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: failed
            image: {{ .Values.maintenance.s3UtilsImage.repository }}:{{ .Values.maintenance.s3UtilsImage.tag }}
            imagePullPolicy: {{ .Values.maintenance.s3UtilsImage.pullPolicy }}
            command: ["/bin/bash"]
            args:
            - -c
            - node autoRetryFailedCRR.js 
            env:
            - name: ENDPOINT
              value: "{{ .Release.Name }}-cloudserver"
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "zenko.retry" . }}
                  key: accesskey
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "zenko.retry" . }}
                  key: secretkey
            - name: MONGODB_REPLICASET
              value: "{{ template "zenko.mongodb-hosts" . }}"
            - name: DRY_RUN
              value: "false"
{{- end -}}
