{{- if .Values.pfsd.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.pfsd.service.name }}
  name: {{ .Values.pfsd.service.name }}
  {{- else }}
  name: {{ template "cosmos.pfsd.fullname" . }}
  {{- end }}
  labels:
    component: pfsd
{{ include "cosmos.labels" . | indent 4 }}
spec:
  type: {{ .Values.pfsd.service.type }}
  ports:
    - port: {{ .Values.pfsd.service.port }}
      targetPort: pfs
      protocol: TCP
      name: http
  selector:
    app: {{ template "cosmos.name" . }}
    component: pfsd
    release: {{ .Release.Name }}
{{- end }}
