apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cosmos.rclone.fullname" . }}
  labels:
    component: rclone
{{ include "cosmos.labels" . | indent 4 }}
data:
  rclone.conf: |-
    [cloudserver]
    type = s3
    provider = Other
    env_auth = true
    endpoint = {{ .Values.rclone.remote.endpoint }}
    location_constraint = {{ .Values.rclone.remote.region }}
