apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cosmos.rclone.fullname" . }}
  labels:
    component: rclone
{{ include "cosmos.labels" . | indent 4 }}
data:
  rclone.conf: |-
    [source]
{{- include "cosmos.rclone.configmap" .Values.rclone.source | indent 4 }}

    [destination]
{{- $dst := merge (default .Values.rclone.destination .Values.rclone.remote) .Values.rclone.destination }}
{{- include "cosmos.rclone.configmap" $dst | indent 4 }}
